---
title: "Rasters.jl"
subtitle: "A DimensionalData extension for GeoSpatial data reading, writing and manipulation"
author:
  - name: Rafael Schouten
    orcid:
    email: rafaelschouten@gmail.com
    affiliation:
      - name: Globe Intstitute, Copenhagen University
      - department: Section for Biodiversity
date: "2024-07-10"
engine: julia
format:
  revealjs:
    theme: [serif, style.scss] # beige blood dark default league moon night serif simple sky solarized
    incremental: true
    toc: false
    toc-depth: 2
    slide-number: true
    overview: true
    code-line-numbers: false
execute:
    echo: true
---

## Read/Write Backends

File types                      | Package
------------------------------- | ----------
Netcdf/hdf5                     | NCDatasets.jl
Grib (read only)                | GRIBDatasets.jl
Zarr (PR nearly done!)          | ZarrDatasets.jl
R grd (simple Mmap data from R) | native
GeoTIFF and everything else     | ArchGDAL.jl


## Backend detection

From filename extension:

```julia
# Single array
rast = Raster("myrasterfile.ext")

# Multi-array
st = RasterStack("myrasterstack.ext")

# Series of rasters or stacks may be detectable from folders
st = RasterSeries("myrasterfolder", Ti(DateTime))
```

# Lazy loading

For manipulating larger-than-memory data

## DiskArrays.jl integration  

Loads dimension names, lookups and other metadata up front with
`lazy=true` keyword in constructors:

```julia
rast = Raster(filename; lazy=true)
```

Still lazy after broadcasts:
```julia
rast10 = rast .* 10
```

Reads from disk only on `getindex`:
```julia
rast10[X=100 .. 135, Y=20 .. 40]
```

Or `read`:
```julia
read(rast10)
```

## Change chunk patterns 
For more efficient lazy reads:
\
```julia
write("rechunked.tif", raster; chunks=(256, 256))
```

## RasterDataSources.jl integration

```{julia}
#| echo: false
ENV["RASTERDATASOURCES_PATH"] = "/home/raf/Data/Raster";
```
\
Load a raster the standard way, from a filename:

```{julia}
using Rasters, RasterDataSources, ArchGDAL
bioclim_filename = RasterDataSources.getraster(WorldClim{BioClim}, 5)
bioclim5 = Raster(bioclim_filename);
```
\
Or just use RasterDataSources syntax directly:

```{julia}
bioclim_filename = Raster(WorldClim{BioClim}, 5);
```

# Plotting

Always the right way up!

## Plots.jl

```{julia}
using Plots
Plots.plot(bioclim5)
```

## Makie.jl

```{julia}
#| echo: false
using CairoMakie
CairoMakie.activate!(type = "png")
```

```{julia}
using CairoMakie
Makie.plot(bioclim5)
```

## GeoMakie.jl

```{julia}
using GeoMakie
fig = Figure();
ga = GeoAxis(fig[1, 1]; dest="+proj=ortho +lon_0=19 +lat_0=72")
Makie.heatmap!(ga, bioclim5; colormap=:isoluminant_cgo_70_c39_n256)
fig
```


# Common GIS methods

## Native rasterization engine

- accepts all GeoInterface.jl geometries
- extremely fast + threaded
  - usually an order of magnitude faster than other packages
- detailed correctness warnings
- consistent behaviour and syntax for:
  - `rasterize`
  - `coverage`
  - `mask`
  - `boolmask`/`missingmask`
  - `zonal`

## Other common methods

- extract
- crop/extend
- trim
- mosaic
- aggregate
- resample

## `mask` + `trim`

```{julia}
#| echo: false
using Rasters: trim
```

Mask climate data wth Norway border (from NaturalEarth.jl), and trim:

```{julia}
using NaturalEarth, Dates, DataFrames
countries = DataFrame(naturalearth("ne_10m_admin_0_countries"))
norway_border = subset(countries, :NAME => ByRow(==("Norway"))).geometry[1]
climate = RasterStack(WorldClim{Climate}, (:tmin, :tmax, :prec, :wind); month=July)
norway_climate = trim(mask(climate; with=norway_border)[Y=0 .. 90]; pad=10)
Plots.plot(norway_climate; size=(1000, 500))
```

## `extract`

Extract climate data at species occurrence points:

```{julia}
#| code-overflow: scroll
using GBIF2
occurrences = GBIF2.occurrence_search("Burramys parvus")
climate = RasterStack(WorldClim{BioClim})
extract(climate, occurrences; name=(:bio1, :bio4, :bio7)) |> DataFrame
```

## `zonal` statistics

```{julia}
#| echo: false
using Rasters, RasterDataSources, ArchGDAL, Dates, DataFrames, NaturalEarth, Statistics
```

Find the hottest and coldest countries in July:

```{julia}
countries = DataFrame(naturalearth("ne_10m_admin_0_countries"))
clim = Raster(WorldClim{Climate}, :tmax; month=July)
countries.july_maxtemp = zonal(Statistics.mean, clim; 
    of=countries, boundary=:touches, progress=false
)
filtered = subset(countries, :july_maxtemp => ByRow(!isnan))
sort!(filtered, :july_maxtemp).NAME
```

# Thanks!

Any problems, make github issues at\https://github.com/rafaqz/Rasters.jl
\
But please include all files in a MWE!
